### ISSUE TITLE
convert ١ ٢ ٣ to 1 2 3

### ISSUE THREAD

**Issue by vetej** [petitssuisses/piwigo-PresyncAutoRename#1]
First of all I want to thank you for this plugins. It helps me alot.
I hope that I could programming in PHP but I can't so I hope that you could help me with this. I have looked at your source code to try to find the commands but I have not succeeded in finding them.

When a filename has a number like ١,٢,٣....etc it will be converted to "-". I just want the number to be in this form 1,2,3. 

People think that those numbers  (1234567890) are english numbers but actually they are arabic numbers. (١٢٣٤٥٦٧٨٩٠) are indian numbers. So I want to convert numbers from indian form to arabic.

Thanks alot.

**Comment by petitssuisses** [comment]
Hi,

Could you attach a photo with such numbers so that I’m sure I use the correct encoding ? 
Thanks

**Comment by vetej** [comment]
![IMG_٢٠١٦١٢٢١_١٢٢٠١٢](https://user-images.githubusercontent.com/75871398/116327812-dfccbf00-a7c7-11eb-9a66-6d2591a69d8c.jpg)

hope you are not hungry.🙂🙂

**Comment by vetej** [comment]
I don't know if you can get the picture name so I write it here.
IMG_٢٠١٦١٢٢١_١٢٢٠١٢.jpg
it should be IMG_122012_20161221.jpg

1=١
2=٢
3=٣
4=٤
5=٥
6=٦
7=٧
8=٨
9=٩
0=٠

**Comment by petitssuisses** [comment]
Implemented in latest Github commit. I will update Piwigo plugins repository. Enjoy ;)

**Comment by petitssuisses** [comment]
(and good appetit !)

**Comment by vetej** [comment]
Thank you so much. I 've tried it on a few files and It works great. I'll apply it on all files. 👍

**Comment by petitssuisses** [comment]
Welcome !
