### ISSUE TITLE
Support for additional sync folders

### ISSUE THREAD

**Issue by zzatihz1** [petitssuisses/piwigo-PresyncAutoRename#5]
Does this plugin support presync for other locations besides galleries? I have another folder that I would like to use presync for but I don't see any way to select a different sync location.

The main Piwigo does allow sync from other folders.

Thank you in advance for any help/support.

**Comment by petitssuisses** [comment]
Hi 
Not today the presync action is only active on the main gallery (the one with id 1) 
It would require a small enhancement but which is not scheduled yet
